#!/usr/bin/env bash
# using while loop and if condition to print Best School 9 times  and Hi 1 times at ninth position

a=0
while ((a < 10))
do
    if ((a == 9))
    then
        echo "Hi"
    fi
    echo "Best School"
    ((a++))
done
