#!/usr/bin/env bash
# using while loop and if condition to print Best School 9 times  and Hi 1 times at ninth position

a=0
while ((a < 10))
do
    if ((a == 3))
    then
        echo "bad luck"
    elif ((a == 7))
    then
        echo "good luck"
    else 
        echo "Best School"
    fi
    ((a++))
done
